version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: llm_gateway_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: llm_gateway
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: llm_gateway_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata: